import type { User, Task } from './types';

export const USERS: User[] = [
  { id: 'user-1', name: 'Alex', avatar: 'https://i.pravatar.cc/150?u=alex', points: 1250 },
  { id: 'user-2', name: 'Maria', avatar: 'https://i.pravatar.cc/150?u=maria', points: 980 },
  { id: 'user-3', name: 'David', avatar: 'https://i.pravatar.cc/150?u=david', points: 1520 },
  { id: 'user-4', name: 'Sarah', avatar: 'https://i.pravatar.cc/150?u=sarah', points: 750 },
  { id: 'user-5', name: 'Ken', avatar: 'https://i.pravatar.cc/150?u=ken', points: 1100 },
];

export const TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Stofzuig de woonkamer',
    description: 'Vergeet de hoeken en onder de bank niet.',
    status: 'To-do',
    priority: 'Hoog',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 3)),
    assigneeId: 'user-1',
    labels: ['Woonkamer'],
    subtasks: [],
    attachments: [],
    isPrivate: false,
    createdAt: new Date(new Date().setDate(new Date().getDate() - 2)),
  },
  {
    id: 'task-2',
    title: 'Maak de badkamer schoon',
    description: 'Maak het toilet, de douche en de wastafel schoon.',
    status: 'In Progress',
    priority: 'Hoog',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 5)),
    assigneeId: 'user-2',
    labels: ['Badkamer'],
    subtasks: [
      { id: 'sub-1', text: 'Maak het toilet schoon', completed: true },
      { id: 'sub-2', text: 'Maak de douche schoon', completed: false },
    ],
    attachments: [],
    isPrivate: false,
    createdAt: new Date(new Date().setDate(new Date().getDate() - 5)),
  },
  {
    id: 'task-3',
    title: 'Dweil de keukenvloer',
    description: 'Gebruik het speciale schoonmaakmiddel voor de tegelvloer.',
    status: 'In Progress',
    priority: 'Midden',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 1)),
    assigneeId: 'user-3',
    labels: ['Keuken'],
    subtasks: [],
    attachments: [],
    isPrivate: false,
    createdAt: new Date(new Date().setDate(new Date().getDate() - 1)),
  },
  {
    id: 'task-4',
    title: 'Maak de ramen schoon',
    description: 'Zowel binnen als buiten.',
    status: 'To-do',
    priority: 'Laag',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 10)),
    assigneeId: 'user-4',
    labels: ['Algemeen'],
    subtasks: [],
    attachments: [],
    isPrivate: false,
    createdAt: new Date(new Date().setDate(new Date().getDate() - 3)),
  },
  {
    id: 'task-5',
    title: 'Stof de meubels af',
    description: 'Stof alle meubels in de woonkamer af.',
    status: 'Done',
    priority: 'Hoog',
    dueDate: new Date(new Date().setDate(new Date().getDate() - 7)),
    assigneeId: 'user-1',
    labels: ['Woonkamer', 'Slaapkamer'],
    subtasks: [],
    attachments: [],
    isPrivate: true,
    createdAt: new Date(new Date().setDate(new Date().getDate() - 14)),
    completedAt: new Date(new Date().setDate(new Date().getDate() - 6)),
  },
  {
    id: 'task-6',
    title: 'Leeg de vaatwasser',
    description: 'Ruim de schone vaat op in de kasten.',
    status: 'To-do',
    priority: 'Midden',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 12)),
    assigneeId: 'user-5',
    labels: ['Keuken'],
    subtasks: [],
    attachments: [],
    isPrivate: false,
    createdAt: new Date(new Date().setDate(new Date().getDate() - 1)),
  },
  {
    id: 'task-7',
    title: 'Maak de oven schoon',
    description: 'Gebruik ovenreiniger en volg de instructies.',
    status: 'Done',
    priority: 'Midden',
    dueDate: new Date(new Date().setDate(new Date().getDate() - 4)),
    assigneeId: 'user-1',
    labels: ['Keuken'],
    subtasks: [],
    attachments: [],
    isPrivate: false,
    createdAt: new Date(new Date().setDate(new Date().getDate() - 8)),
    completedAt: new Date(new Date().setDate(new Date().getDate() - 3)),
  },
   {
    id: 'task-8',
    title: 'Organiseer de voorraadkast',
    description: 'Controleer de houdbaarheidsdatums en gooi weg wat over datum is.',
    status: 'Done',
    priority: 'Laag',
    dueDate: new Date(new Date().setDate(new Date().getDate() - 10)),
    assigneeId: 'user-2',
    labels: ['Keuken'],
    subtasks: [],
    attachments: [],
    isPrivate: false,
    createdAt: new Date(new Date().setDate(new Date().getDate() - 12)),
    completedAt: new Date(new Date().setDate(new Date().getDate() - 9)),
  }
];
