
export const roadmapData = {
    "Fundamenteel Taakbeheer (Basis)": [
      { id: 1001, title: "Taakcreatie & Eigenschappen", description: "Prioriteit, labels, toewijzing en deadlines.", completed: true },
      { id: 1002, title: "Taakstatussen & Workflow", description: "Configureerbare statussen met kleurcodering (Te Doen, In Uitvoering, etc.).", completed: true },
      { id: 1003, title: "Subtaken (Sub-tasks)", description: "Hiërarchische, afvinkbare subtaken binnen een hoofdtaak.", completed: true },
      { id: 1004, title: "Taakafhankelijkheden ('Blocked by')", description: "Voorkom dat een taak start voordat een andere is voltooid.", completed: true },
      { id: 1005, title: "Taaktemplates", description: "Sla taken op als templates voor hergebruik.", completed: true },
      { id: 1006, title: "Bestands- & Linkbijlagen", description: "Voeg URL's toe aan taken.", completed: true },
      { id: 1007, title: "Persoonlijke Taken & Zichtbaarheid", description: "Markeer taken als privé, alleen zichtbaar voor de maker en toegewezene.", completed: true },
      { id: 1008, title: "Historie & Logging", description: "Volledige, zichtbare geschiedenis van alle wijzigingen per taak.", completed: true },
      { id: 1009, title: "Taak Klonen", description: "Dupliceer een bestaande taak met één klik.", completed: true },
      { id: 1010, title: "Bulk Taakoperaties", description: "Bewerk status, prioriteit en toegewezene voor meerdere taken tegelijk.", completed: true },
      { id: 1011, title: "Handmatige Taakvolgorde", description: "Sleep taken in de gewenste volgorde binnen een statuskolom.", completed: true },
      { id: 1012, title: "Rich Text Editor", description: "Opmaakmogelijkheden (vet, cursief, lijsten) in beschrijvingen en comments.", completed: true },
      { id: 1013, title: "Recycle Bin / Prullenbak", description: "Herstel geannuleerde taken vanuit de 'Geannuleerd' kolom.", completed: true },
      { id: 1014, title: "Geavanceerde Terugkerende Taken", description: "Complexe herhalingspatronen (bv. 'elke 3e donderdag van de maand').", completed: true },
      { id: 1015, title: "Persoonlijke Herinneringen (/remindme)", description: "Vraag de bot om je ergens aan te herinneren.", completed: true },
    ],
    "Fundamenteel Taakbeheer (Verdieping)": [
      { id: 1, title: "Conditionele Custom Fields", description: "Veld Y tonen als veld X waarde Z heeft.", completed: false },
      { id: 2, title: "Terugkerende Subtaken", description: "Enkel een subtaak herhaalt, niet de hele taak.", completed: false },
      { id: 3, title: "Private Subtaken", description: "Alleen zichtbaar voor de toegewezene en projectmanager.", completed: true },
      { id: 4, title: "Lead & Lag Time in Afhankelijkheden", description: "Start 2 dagen voor of na een andere taak eindigt.", completed: true },
      { id: 5, title: "Taak Ratings", description: "Geef een voltooide taak 1-5 sterren voor kwaliteitsmeting.", completed: true },
      { id: 6, title: "Taak Checklist Templates", description: "Opslaan en hergebruiken van sets subtaken.", completed: true },
      { id: 7, title: "'Blokkerende' status", description: "Maakt visueel duidelijk dat een taak geblokkeerd is en waarom.", completed: true },
      { id: 8, title: "Multi-assign", description: "Meerdere personen verantwoordelijk maken voor één taak.", completed: true },
      { id: 9, title: "Taak Splitsen", description: "Splits een te grote taak in twee of meer aparte taken.", completed: true },
    ],
    "Geavanceerd Project- & Resource Management": [
      { id: 1022, title: "Task Review & Approval Workflow", description: "Formele goedkeuringsstap ('In Review') voor voltooide taken.", completed: true },
      { id: 1023, title: "Effort Estimation (Story Points)", description: "Schat complexiteit in met Story Points.", completed: true },
      { id: 1024, title: "Gantt Chart View", description: "Visuele tijdlijn-weergave van projecten.", completed: true },
      { id: 1025, title: "Actieve Tijdregistratie", description: "Start/stop een timer per taak voor precieze tijdsmeting.", completed: true },
      { id: 1027, title: "Skills & Competency Matrix", description: "Tag gebruikers met vaardigheden voor betere toewijzing.", completed: true },
      { id: 10, title: "Programma Management", description: "Groepeer projecten in programma's met eigen doelen/KPI's.", completed: false },
      { id: 11, title: "Scenario Planning / \"What-if\" Analyse", description: "Simuleer impact van resource-wijzigingen.", completed: false },
      { id: 12, title: "Gantt Chart Snapshots & Versiebeheer", description: "Vergelijk de planning met eerdere versies.", completed: false },
      { id: 13, title: "Headcount Planning", description: "Plan toekomstige personeelsbehoefte op projectniveau.", completed: false },
      { id: 14, title: "Resource Vervanging", description: "Snel alle taken van persoon A overzetten naar persoon B.", completed: false },
      { id: 15, title: "RACI Matrix Generator", description: "Genereer een Responsible, Accountable, Consulted, Informed matrix.", completed: false },
      { id: 16, title: "Automatische Resource Leveling", description: "Verschuif taken automatisch om overbelasting te voorkomen.", completed: false },
      { id: 17, title: "Team-specifieke Werkuren en Feestdagen", description: "Definieer werkuren en vrije dagen per team.", completed: false },
      { id: 18, title: "Project Scorecards", description: "Configureerbare gezondheids-score per project.", completed: false },
      { id: 19, title: "Skills Gap Analyse", description: "Identificeer missende vaardigheden voor een project.", completed: false },
      { id: 26, title: "Workload Capacity Planning", description: "Visualiseer de werkdruk per teamlid.", completed: false },
      { id: 28, title: "Project Milestones", description: "Definieer belangrijke mijlpalen binnen een project.", completed: false },
      { id: 29, title: "Budget & Kostentracking", description: "Houd budgetten en gemaakte kosten bij per project of taak.", completed: false },
      { id: 30, title: "Resource Planning (Niet-menselijk)", description: "Wijs apparatuur of ruimtes toe aan taken.", completed: false },
      { id: 31, title: "Afhankelijkheden Tussen Projecten", description: "Maak hele projecten van elkaar afhankelijk.", completed: false },
      { id: 32, title: "Geavanceerd Template Beheer", description: "Versiebeheer en conditionele logica in templates.", completed: false },
      { id: 33, title: "Project Portfolio Management", description: "Groepeer en beheer gerelateerde projecten als een portfolio.", completed: false },
      { id: 34, title: "Gantt Chart met Critical Path Analysis", description: "Identificeer automatisch het kritieke pad in een project.", completed: false },
      { id: 35, title: "Time Off & Availability Management", description: "Gebruikers kunnen hun afwezigheid aangeven, wat zichtbaar is in de planning.", completed: false },
      { id: 36, title: "Facturatie op basis van Tijdregistratie", description: "Genereer factuurvoorstellen op basis van gelogde tijd.", completed: false },
      { id: 37, title: "Risico Register", description: "Een aparte module per project om risico's te identificeren, te beoordelen en te mitigeren.", completed: false },
      { id: 38, title: "Stakeholder Management", description: "Wijs stakeholders toe aan projecten met specifieke communicatievoorkeuren.", completed: false },
      { id: 39, title: "Project Baselines", description: "'Bevries' een projectplan om de voortgang te meten ten opzichte van het originele plan.", completed: false },
    ],
    "Artificiële Intelligentie & Smart-Functionaliteit": [
      { id: 1040, title: "AI Smart Assignment", description: "Stelt de beste persoon voor een taak voor op basis van data.", completed: true },
      { id: 1041, title: "AI-Assisted Task Breakdown", description: "Genereert subtaken voor een complexe hoofdtaak.", completed: true },
      { id: 1042, title: "AI-Powered Task Summarization", description: "Vat lange discussies in taak-comments samen.", completed: true },
      { id: 1043, title: "NLP voor Taakcreatie & Herinneringen", description: "Creëer taken en reminders met gewone zinnen (bv. /remindme).", completed: true },
      { id: 1044, title: "Smart Search (Natural Language Query)", description: "Doorzoek de database met complexe vragen via de commandobalk.", completed: true },
      { id: 1047, title: "AI-Powered Risico-Identificatie", description: "Analyseert taakteksten op potentiële risicowoorden.", completed: true },
      { id: 1049, title: "AI Voice-to-Task & Voice Control", description: "Dicteer taken en commando's via spraak.", completed: true },
      { id: 1052, title: "AI-Suggested Taakprioritering", description: "Geeft een voorzet voor de prioriteit op basis van inhoud en context.", completed: true },
      { id: 1051, title: "AI-Powered Image Generation", description: "Genereer een omslagfoto voor een taak op basis van de titel.", completed: true },
      { id: 1050, title: "AI Multi-Speaker Text-to-Speech", description: "Zet een discussie om in een gesprek met meerdere stemmen.", completed: true },
      { id: 20, title: "AI Team Composition Suggester", description: "Stelt het ideale team voor een nieuw project voor.", completed: false },
      { id: 21, title: "AI Communicatie 'Health' Score", description: "Analyseert reactietijden, sentiment etc.", completed: false },
      { id: 22, title: "AI Goal Setting Assistant", description: "Helpt bij het formuleren van SMART-doelen.", completed: false },
      { id: 23, title: "AI-powered 'Vergadering naar Taken'", description: "Analyseert transcript en stelt actiepunten voor.", completed: true },
      { id: 24, title: "AI voor Automatische Tagging", description: "Suggereert labels op basis van taakinhoud.", completed: true },
      { id: 25, title: "AI Kennisconflictdetectie", description: "Signaleert tegenstrijdige informatie in taken/docs.", completed: false },
      { id: 26, title: "AI Burnout Voorspelling", description: "Signaleert risico op basis van werkpatronen.", completed: false },
      { id: 27, title: "AI-Powered Onboarding Pad", description: "Genereert een persoonlijk inwerktraject voor nieuwe gebruikers.", completed: false },
      { id: 28, title: "AI Leercurve Analyse", description: "Voorspelt hoe snel een team productief wordt met een nieuwe technologie.", completed: false },
      { id: 29, title: "AI-suggested 'Next Best Action' voor een taak.", completed: false },
      { id: 45, title: "AI Predictive Analysis & Risk Detection", description: "Waarschuwt proactief voor projectvertragingen.", completed: false },
      { id: 46, title: "AI-Generated Reports", description: "Maak rapporten op basis van een prompt in natuurlijke taal.", completed: false },
      { id: 48, title: "AI-Suggested Optimal Workflow Paths", description: "Stelt de meest efficiënte status-volgorde voor per taaktype.", completed: false },
      { id: 50, title: "Automatische Detectie van Dubbele Taken", description: "Signaleert mogelijke duplicaten bij aanmaak.", completed: false },
      { id: 51, title: "AI-Powered Sentiment Analyse", description: "Analyseert de toon van de communicatie in comments.", completed: false },
      { id: 53, title: "AI Anomaly Detection", description: "Detecteert ongebruikelijke patronen in de voortgang of tijdregistratie.", completed: false },
    ],
    "Community, Gamification & HR": [
      { id: 1054, title: "Beloningssysteem", description: "Experience Points (EXP) en Punten.", completed: true },
      { id: 1055, title: "Achievements & Badges", description: "Ontgrendelbare prestaties voor mijlpalen.", completed: true },
      { id: 1056, title: "Leaderboards", description: "Scoreborden per team/organisatie.", completed: true },
      { id: 1057, title: "Karma- & Bedanksysteem", description: "Stimuleer positieve interactie door collega's te bedanken.", completed: true },
      { id: 30, title: "'Kudos' Tipping", description: "Geef een deel van je punten aan een collega als bedankje.", completed: true },
      { id: 31, title: "Mentorschap Programma", description: "Koppel ervaren gebruikers aan nieuwkomers.", completed: false },
      { id: 32, title: "Dynamische Leaderboards", description: "Op basis van specifieke tags, bv. \"Top Bug Fixer\".", completed: false },
      { id: 33, title: "Community-driven 'Chore of the Week'", description: "Een uitdagende taak voor iedereen.", completed: false },
      { id: 34, title: "Virtuele 'Team Room'", description: "Een 2D/isometrische ruimte waar avatars van teamleden zijn.", completed: false },
      { id: 35, title: "User-Generated Content Challenges", description: "Bv. 'maak de beste taak-template'.", completed: false },
      { id: 36, title: "Project Post-Mortem Badges", description: "Badges voor succesvol afgeronde projecten.", completed: false },
      { id: 58, title: "'Help Wanted' Board", description: "Vraag om hulp bij specifieke taken.", completed: false },
      { id: 59, title: "Team-Based Challenges & Competities", description: "Stel doelen voor teams met een beloning.", completed: false },
      { id: 60, title: "Skill Endorsements", description: "Gebruikers kunnen elkaars vaardigheden onderschrijven.", completed: false },
      { id: 61, title: "Ideeënbus & Feature Request Voting", description: "Laat gebruikers meebeslissen over de toekomst van Chorey.", completed: false },
      { id: 62, title: "Puntenwinkel", description: "Wissel verdiende punten in voor cosmetische items.", completed: false },
      { id: 63, title: "Guilds / Clans", description: "Laat gebruikers permanente groepen vormen voor competities en samenwerking.", completed: false },
    ],
    "Het Webdashboard, UI & UX": [
      { id: 1064, title: "Geavanceerd Webdashboard", description: "Het centrale beheerplatform.", completed: true },
      { id: 1065, title: "Aanpasbare Dashboard Widgets", description: "Stel je eigen dashboard samen met diverse grafieken en statistieken.", completed: true },
      { id: 1066, title: "Keyboard Shortcuts (Webdashboard)", description: "Sneltoetsen voor efficiëntie.", completed: true },
      { id: 1067, title: "Gebruikersprofielen", description: "Bekijk statistieken en taken van een gebruiker.", completed: true },
      { id: 1068, title: "Kalender-, Bord- & Lijstweergave", description: "Visualiseer taken op meerdere manieren.", completed: true },
      { id: 1072, title: "Command Palette (Cmd/Ctrl+K)", description: "Een centrale interface om alles te besturen.", completed: true },
      { id: 1074, title: "Aanpasbare Views (Filteren)", description: "Filter taken op basis van diverse criteria.", completed: true },
      { id: 1075, title: "Dark Mode & Theming", description: "Donkere modus en andere kleurenthema's voor de interface.", completed: true },
      { id: 37, title: "Publiek Deelbare Dashboards", description: "Read-only link voor externen.", completed: false },
      { id: 38, title: "Horloge Companion App", description: "Apple Watch/Wear OS.", completed: false },
      { id: 39, title: "Globale Inbox", description: "Één plek voor alle @mentions, reviews, notificaties.", completed: false },
      { id: 40, title: "Multi-Window / Tab Support", description: "Ondersteuning voor meerdere vensters in de webapp.", completed: false },
      { id: 41, title: "'Mijn Week' view", description: "Een persoonlijke, automatische planning.", completed: false },
      { id: 42, title: "Gebruikersstatus & Aanwezigheid", description: "Online, Afwezig, In een meeting, etc.", completed: false },
      { id: 43, title: "Snelheid van Interface-animaties instelbaar", description: "Pas de snelheid van animaties aan.", completed: false },
      { id: 44, title: "Drag & Drop Taakcreatie vanuit bestanden", description: "Sleep bestanden om taken aan te maken.", completed: false },
      { id: 45, title: "Visuele Workflow Editor", description: "Bouw workflows met een drag-and-drop interface.", completed: false },
      { id: 46, title: "Geavanceerde Zoekfilters Opslaan", description: "Sla complexe filtersets op voor hergebruik.", completed: false },
      { id: 47, title: "White-labeling / Custom Branding", description: "Pas het platform aan met eigen logo en kleuren.", completed: false },
      { id: 48, title: "Focus Mode", description: "Een afleidingsvrije interface om te focussen op de huidige taak.", completed: false },
      { id: 49, title: "Toegankelijkheidsverbeteringen (A11y)", description: "Volledige ondersteuning voor screenreaders en toetsenbordnavigatie.", completed: false },
      { id: 69, title: "Offline Modus (PWA)", description: "Werk offline en synchroniseer later.", completed: false },
      { id: 70, title: "Dedicated Mobile Companion App", description: "Native app voor iOS en Android.", completed: false },
      { id: 71, title: "Meertalige Interface", description: "Ondersteuning voor meerdere talen.", completed: false },
      { id: 73, title: "In-App Onboarding & Feature Tours", description: "Interactieve gidsen voor nieuwe features.", completed: false },
    ],
    "Integraties & API": [
      { id: 1079, title: "Data Export (CSV)", description: "Exporteer taken naar CSV.", completed: true },
      { id: 1080, title: "Data Import (CSV)", description: "Importeer taken vanuit een CSV-bestand.", completed: true },
      { id: 50, title: "Native Automation Builder", description: "Ingebouwde 'Zapier'-light.", completed: false },
      { id: 51, title: "GitLab & Bitbucket Integraties", description: "Koppel taken aan GitLab/Bitbucket.", completed: false },
      { id: 52, title: "Figma / Adobe XD / Sketch Integratie", description: "Koppel design-bestanden aan taken.", completed: false },
      { id: 53, title: "CRM Integraties", description: "HubSpot, Salesforce.", completed: false },
      { id: 54, title: "Boekhoudsoftware Integraties", description: "QuickBooks, Xero.", completed: false },
      { id: 55, title: "Support Ticket Systeem Integraties", description: "Zendesk, Intercom.", completed: false },
      { id: 56, title: "Slack/Teams Bot 2.0", description: "Interactie met modals en knoppen.", completed: false },
      { id: 57, title: "GraphQL API naast de REST API", description: "Bied een GraphQL API aan.", completed: false },
      { id: 58, title: "Developer Sandbox Environment", description: "Een testomgeving voor ontwikkelaars.", completed: false },
      { id: 59, title: "Embedded Views", description: "Embed een Chorey board in een andere webpagina.", completed: false },
      { id: 60, title: "Browser Extensie", description: "Creëer taken vanaf elke webpagina.", completed: false },
      { id: 61, title: "Outlook / Gmail Add-on", description: "Integreer Chorey in je e-mailclient.", completed: false },
      { id: 80, title: "Google Calendar Integratie", description: "Synchroniseer deadlines met je agenda.", completed: false },
      { id: 81, title: "GitHub Integratie", description: "Koppel taken aan issues en pull requests.", completed: false },
      { id: 82, title: "Exposed REST API voor Ontwikkelaars", description: "Laat derden bouwen op Chorey.", completed: false },
      { id: 83, title: "Microsoft Teams Integratie", description: "Volledige functionaliteit binnen MS Teams.", completed: false },
      { id: 84, title: "Zapier / Make (Integromat) Integratie", description: "Verbind Chorey met duizenden andere apps.", completed: false },
      { id: 85, title: "Cloud Storage Integraties", description: "Koppel bestanden direct vanuit Google Drive, OneDrive, Dropbox.", completed: false },
      { id: 86, title: "Email-to-Task Gateway", description: "Maak taken aan door een e-mail te sturen naar een uniek projectadres.", completed: false },
      { id: 87, title: "Webhooks", description: "Stuur real-time updates naar externe systemen bij gebeurtenissen in Chorey.", completed: false },
    ],
    "Notificaties & Communicatie": [
      { id: 1088, title: "Flexibel Notificatiesysteem", description: "Notificaties voor @mentions en toewijzingen.", completed: true },
      { id: 1090, title: "Notificatie \"Snooze\" Functionaliteit", description: "Stel een notificatie uit.", completed: true },
      { id: 62, title: "Push Notificaties met Actieknoppen", description: "Bv. 'Voltooien', 'Snooze'.", completed: false },
      { id: 63, title: "'Mute' specifieke taak- of project-threads", description: "Stop notificaties voor een specifieke taak.", completed: false },
      { id: 64, title: "Notificatie Prioriteit", description: "Alleen 'Urgent' @mentions sturen een push notificatie.", completed: false },
      { id: 65, title: "Ingebouwde Aankondigingen-module voor beheerders", description: "Stuur aankondigingen naar alle gebruikers.", completed: false },
      { id: 66, title: "'Leesbevestiging' voor belangrijke comments of updates", description: "Zie wie een belangrijke update heeft gelezen.", completed: false },
      { id: 89, title: "Dagelijks Overzicht", description: "Configureerbaar kanaal voor dagelijkse updates.", completed: false },
      { id: 91, title: "Verbeterde @mentions en Taakdiscussies", description: "Rijkere discussies met threads.", completed: true },
      { id: 92, title: "Notificatie Digest", description: "Ontvang een samenvatting (dagelijks/wekelijks) van alle updates.", completed: false },
    ],
    "Veiligheid, Compliance & Beheer": [
      { id: 1093, title: "Geavanceerd Rechtenbeheer (RBAC)", description: "Definieer rollen (Eigenaar, Beheerder, Lid) met specifieke permissies.", completed: true },
      { id: 67, title: "Data Masking voor gevoelige projecten", description: "Verberg gevoelige informatie.", completed: false },
      { id: 68, title: "Verplichte 2FA voor bepaalde rollen", description: "Forceer Two-Factor Authentication.", completed: false },
      { id: 69, title: "API Rate Limiting & Key Management", description: "Beheer API-toegang.", completed: false },
      { id: 70, title: "Sessie Management", description: "Zie en beëindig actieve login-sessies.", completed: false },
      { id: 71, title: "Gebruikersgroepen met overervende permissies", description: "Groepeer gebruikers en wijs permissies toe.", completed: false },
      { id: 72, title: "'Impersonate User' functie voor support/admins", description: "Log in als een andere gebruiker.", completed: false },
      { id: 94, title: "Two-Factor Authentication (2FA)", description: "Verbeterde accountbeveiliging.", completed: false },
      { id: 95, title: "Uitgebreide Audit Logs voor Beheerders", description: "Gedetailleerde logging van alle acties.", completed: false },
      { id: 96, title: "Single Sign-On (SSO)", description: "Integratie met SAML, Google, Microsoft.", completed: false },
      { id: 97, title: "Data Residency Opties", description: "Kies de geografische locatie voor dataopslag.", completed: false },
      { id: 98, title: "Gast- / Klanttoegang", description: "Geef externe gebruikers beperkte toegang.", completed: false },
      { id: 99, title: "IP Whitelisting", description: "Beperk toegang tot specifieke IP-adressen.", completed: false },
    ],
    "Analytics & Reporting": [
      { id: 73, title: "Custom Report Builder", description: "Drag-and-drop rapportagebouwer.", completed: false },
      { id: 74, title: "Cycle & Lead Time Reports", description: "Voor Kanban/Agile teams.", completed: false },
      { id: 75, title: "Cost of Delay Analyse", description: "Analyseer de kosten van vertraging.", completed: false },
      { id: 76, title: "Gebruikersprestatie Dashboards", description: "Individueel en team.", completed: false },
      { id: 77, title: "Monte Carlo Simulatie voor projectvoorspellingen", description: "Voorspel projectuitkomsten.", completed: false },
      { id: 78, title: "Project Volatiliteit Index", description: "Hoe vaak deadlines/scope veranderen.", completed: false },
      { id: 79, title: "'Time in Status' rapportages", description: "Identificeer knelpunten.", completed: false },
      { id: 80, title: "Automatisch Geplande Rapportage", description: "E-mail rapport X elke maandag.", completed: false },
    ],
    "Kennisbeheer & Documentatie": [
      { id: 81, title: "Geïntegreerde Wiki/Docs per project", description: "Een kennisbank per project.", completed: false },
      { id: 82, title: "Beslissingslogboek (Decision Log)", description: "Leg belangrijke beslissingen vast.", completed: false },
      { id: 83, title: "Automatisch gegenereerde 'Project Closeout' documentatie", description: "Genereer een einddocument.", completed: false },
      { id: 84, title: "Globale, doorzoekbare kennisbank", description: "Zoek over alle projecten heen.", completed: false },
      { id: 85, title: "Link documentatie direct aan specifieke workflow-statussen", description: "Koppel documentatie aan een status.", completed: false },
      { id: 86, title: "Versiebeheer voor documenten", description: "Houd wijzigingen in documenten bij.", completed: false },
      { id: 87, title: "'Lessons Learned' database", description: "Een database voor geleerde lessen.", completed: false },
    ],
    "Financiën & Facturatie": [
      { id: 88, title: "Offerte- en Factuurcreatie", description: "Maak offertes en facturen aan.", completed: false },
      { id: 89, title: "Uurtarieven per gebruiker, project of taaktype", description: "Stel verschillende uurtarieven in.", completed: false },
      { id: 90, title: "Kostenregistratie (declaratiemodule)", description: "Dien declaraties in.", completed: false },
      { id: 91, title: "Winstgevendheid Rapporten per project/klant", description: "Analyseer de winstgevendheid.", completed: false },
      { id: 92, title: "CapEx vs. OpEx tracking", description: "Volg kapitaal- en operationele uitgaven.", completed: false },
      { id: 93, title: "Budget vs. Actuals real-time dashboard", description: "Vergelijk budgetten met de realiteit.", completed: false },
    ],
    "Klant & Externe Samenwerking": [
      { id: 94, title: "Klantenportaal", description: "Gebrandmerkte, simpele weergave voor klanten.", completed: false },
      { id: 95, title: "Publieke Taak Indieningsformulieren", description: "Voor support/feedback.", completed: false },
      { id: 96, title: "Beeld-annotatie & Proofing", description: "Commentaar direct op afbeeldingen.", completed: false },
      { id: 97, title: "Externe goedkeuringsworkflows", description: "Laat externen taken goedkeuren.", completed: false },
      { id: 98, title: "Deelbare 'Project Status' pagina's", description: "Deel de status van een project.", completed: false },
    ],
    "Persoonlijke Productiviteit & Welzijn": [
      { id: 99, title: "Geïntegreerde Pomodoro Timer", description: "Een timer voor focus-sessies.", completed: false },
      { id: 100, title: "'Einde van de Dag' afronding", description: "Prompt om de dag te reviewen.", completed: false },
      { id: 101, title: "'Do Not Disturb' schema's", description: "Stel periodes in waarin je niet gestoord wilt worden.", completed: false },
      { id: 102, title: "Persoonlijke Goal Tracking", description: "Los van projecttaken.", completed: false },
      { id: 103, title: "Integratie met mindfulness-apps", description: "Headspace/Calm.", completed: false },
      { id: 104, title: "Werk-privé balans dashboard", description: "Analyse van werkuren.", completed: false },
      { id: 105, title: "Muziek voor Focus' integratie", description: "Spotify.", completed: false },
      { id: 106, title: "Dagelijkse 'Highlight Taak'", description: "Kies 1-3 belangrijkste taken.", completed: false },
    ],
    "Hyper-Automatisering & Interne Processen": [
      { id: 107, title: "HR Onboarding & Offboarding Workflow Automation", description: "Automatisch taken aanmaken voor IT, HR, etc.", completed: false },
      { id: 108, title: "IT Servicedesk & Hardware Request Workflows", description: "Workflows voor IT-verzoeken.", completed: false },
      { id: 109, title: "Automatische Taak-specifieke Communicatiekanalen", description: "Genereert een Slack-kanaal per taak met tag 'urgent'.", completed: false },
      { id: 110, title: "A/B Testing Framework voor Workflows", description: "Test welke workflow-variant efficiënter is.", completed: false },
      { id: 111, title: "'Office Hours' Planning", description: "Voor experts om hun beschikbaarheid voor vragen aan te bieden.", completed: false },
      { id: 112, title: "Besluitvormings-frameworks Templates", description: "DACI, RAPID.", completed: false },
    ],
    "Compliance, Legal & Security (Verdieping)": [
      { id: 113, title: "GDPR Data Subject Request (DSR) Workflow", description: "Workflow voor GDPR-verzoeken.", completed: false },
      { id: 114, title: "ISO 27001 Compliance Reporting & Evidence Pack", description: "Rapportage voor ISO 27001.", completed: false },
      { id: 115, title: "E-Discovery & Legal Hold Module", description: "Bewaar data voor juridische doeleinden.", completed: false },
      { id: 116, title: "Service Level Agreement (SLA) Tracking & Reporting", description: "Volg en rapporteer over SLA's.", completed: false },
      { id: 117, title: "Emergency Alert System", description: "Voor P1-incidenten of bedrijfsbrede noodgevallen.", completed: false },
    ],
    "Samenwerking & Communicatie (Next-Gen)": [
      { id: 118, title: "Real-time Collaborative Task Editing", description: "Meerdere mensen typen tegelijk in een beschrijving.", completed: false },
      { id: 119, title: "Ingebouwde Digitale Whiteboards per Project", description: "Miro-light functionaliteit.", completed: false },
      { id: 120, title: "Video- en Audio-opmerkingen in Taken", description: "Laat video- of audioberichten achter.", completed: false },
      { id: 121, title: "Real-time Vertaling van Opmerkingen", description: "Vertaal opmerkingen en beschrijvingen.", completed: false },
      { id: 122, title: "Team Health & Morale Surveys", description: "Periodieke, anonieme check-ins.", completed: false },
    ],
    "Hardware, IoT & Fysieke Wereld": [
      { id: 123, title: "NFC/QR Code Taakinteractie", description: "Scan een code om een taak te starten/stoppen/voltooien.", completed: false },
      { id: 124, title: "Smart Speaker Integratie", description: "Google Assistant, Alexa voor taakupdates en -creatie.", completed: false },
      { id: 125, title: "Geofencing voor Automatische Taakupdates", description: "bv. 'Aangekomen op locatie X' triggert taakstatus.", completed: false },
    ],
    "Educatie, Training & LMS-functionaliteit": [
      { id: 126, title: "Leerpaden & Trainingsprojecten", description: "Definieer een reeks taken/docs als een 'cursus'.", completed: false },
      { id: 127, title: "Vaardigheidstoetsing & Certificering", description: "Koppel een 'quiz' aan een taak om een skill te valideren.", completed: false },
    ],
    "Marketplace & Ecosysteem": [
      { id: 128, title: "Template Marketplace", description: "Community-gedreven marktplaats voor project- en taaktemplates.", completed: false },
      { id: 129, title: "Custom Widget Marketplace", description: "Ontwikkelaars kunnen dashboard-widgets bouwen en delen/verkopen.", completed: false },
      { id: 130, title: "Interne Valuta voor Resource-uitwisseling", description: "Teams kunnen 'credits' gebruiken om resources van elkaar te 'lenen'.", completed: false },
    ],
    "Next-Gen UI & Visualisatie": [
      { id: 131, title: "VR/AR Project Visualisatie", description: "'The Project Room' om data in 3D te zien.", completed: false },
      { id: 132, title: "Conversational UI", description: "Een chat-first interface als primair interactiemodel.", completed: false },
      { id: 133, title: "Globale Activiteit Heatmap", description: "Visualiseer waar en wanneer het meeste werk gebeurt.", completed: false },
    ],
    "People Ops & Strategie": [
      { id: 134, title: "OKR & Performance Review Module", description: "Beheer OKR's en functioneringsgesprekken.", completed: false },
      { id: 135, title: "1-op-1 Meeting Agendaplanner & Notulen", description: "Plan en documenteer 1-op-1 gesprekken.", completed: false },
      { id: 136, title: "Autonome AI Project Coördinator", description: "Een AI die basis follow-ups en rapportages doet.", completed: false },
      { id: 137, title: "AI-gestuurde Project Refactoring", description: "Analyseert complexe projecten en stelt vereenvoudiging voor.", completed: false },
      { id: 138, title: "Interne Bug Bounty Programma's", description: "Beheer meldingen en beloningen.", completed: false },
    ],
    "Financiën & Bedrijfsvoering": [
      { id: 139, title: "Inkooporder (Purchase Order) Module", description: "Beheer inkooporders.", completed: false },
      { id: 140, title: "Declaratiebeheer & Goedkeuring", description: "Beheer declaraties.", completed: false },
      { id: 141, title: "Contract Lifecycle Management (CLM) Integratie", description: "Integreer met CLM-systemen.", completed: false },
      { id: 142, title: "Digital Asset Management (DAM) Integratie", description: "Integreer met DAM-systemen.", completed: false },
    ],
    "Marketing & Sales": [
      { id: 143, title: "Customer Success Playbooks", description: "Standaard projecten voor nieuwe klanten.", completed: false },
      { id: 144, title: "Competitor Tracking Project Templates", description: "Templates om concurrenten te volgen.", completed: false },
      { id: 145, title: "Marktintroductie (Go-to-Market) Plan Template", description: "Template voor marktintroducties.", completed: false },
    ],
    "Ontwikkelaars & IT": [
      { id: 146, title: "API Versioning & Deprecation Management", description: "Beheer API-versies.", completed: false },
      { id: 147, title: "'Shadow IT' Detectie", description: "Analyseert API-verkeer om ongeautoriseerde tools te vinden.", completed: false },
      { id: 148, title: "Automatische Documentatie Generator", description: "Analyseert taken met een 'code'-tag en maakt een wiki-pagina.", completed: false },
    ],
    "Diverse & Innovatief": [
      { id: 149, title: "Printbare Project Samenvattingen/Rapporten", description: "Geoptimaliseerd voor PDF/print.", completed: false },
      { id: 150, title: "Carbon Footprint Tracking per Project", description: "Schatting van de ecologische impact.", completed: false },
      { id: 151, title: "Gebruikerssegmentatie voor Gerichte In-App Communicatie", description: "Stuur gerichte berichten.", completed: false },
      { id: 152, title: "'No-Code' Mobiele App Bouwer voor specifieke workflows", description: "bv. een app voor alleen inspecties.", completed: false },
      { id: 153, title: "'Failure Mode and Effects Analysis' (FMEA) Template & Register", description: "Template voor FMEA.", completed: false },
      { id: 154, title: "Taak Prioriteringsmatrix", description: "Eisenhower, MoSCoW, etc. als ingebouwde view.", completed: false },
      { id: 155, title: "'Focus Playlist' Generator op basis van taaktype", description: "AI stelt Spotify playlist voor.", completed: false },
      { id: 156, title: "Voorspellende Resource Allocatie", description: "AI voorspelt toekomstige knelpunten en stelt verschuivingen voor.", completed: false },
    ]
  };
