
import type { Phase } from '../types';

export const phase14: Phase = {
  name: "Fase 14: AI Agent Autonomie",
  description: "De AI evolueren van een reactieve assistent naar een proactieve, autonome teamgenoot.",
  features: [
    { id: 14001, title: "AI-gestuurde 'Goal-to-Project' Converter", description: "Laat gebruikers een hoog-over doel beschrijven (bv. 'Lanceer onze nieuwe mobiele app in Q4'). De AI analyseert dit doel en genereert een compleet, gestructureerd projectplan met voorgestelde taken, subtaken, afhankelijkheden en deadlines.", completed: false },
    { id: 14002, title: "Continue Modelverbetering", description: "Implementeer een MLOps-pipeline waarbij de AI-modellen (Genkit flows) periodiek automatisch worden gefinetuned op basis van de geanonimiseerde feedback die gebruikers geven via de duim omhoog/omlaag-knoppen.", completed: false },
    { id: 14003, title: "AI Vergadering Planner", description: "Een AI-agent die, wanneer een vergadering nodig is voor een taak, de agenda's van de deelnemers (via de Google/Outlook-integratie) analyseert en de optimale tijd voorstelt, rekening houdend met hun huidige werklast in Chorey.", completed: false },
    { id: 14004, title: "AI Project Archivist", description: "Een achtergrond-agent die periodiek projecten analyseert. Als een project al lange tijd inactief is (geen nieuwe taken, geen updates), stelt de agent aan de projecteigenaar voor om het project te archiveren om de werkruimte opgeruimd te houden.", completed: false },
    { id: 14005, title: "AI Sentiment Analyse", description: "De AI monitort commentaarthreads op tekenen van frictie, negativiteit of frustratie. Indien gedetecteerd, kan het discreet een projectmanager of teamleider waarschuwen voor mogelijke team-issues die aandacht vereisen.", completed: false },
    { id: 14006, title: "AI 'Daily Stand-up' Assistent", description: "De AI vraagt dagelijks via een in-app notificatie of chat aan teamleden wat ze gisteren hebben gedaan, wat ze vandaag gaan doen en wat hun blockers zijn. Vervolgens genereert het een beknopt, samenvattend rapport voor de manager.", completed: false },
    { id: 14007, title: "Autonome Taakuitvoering (experimenteel)", description: "Voor zeer specifieke, herhaalbare taken (bv. 'Genereer wekelijks rapport X'), geef de AI de mogelijkheid om de taak volledig autonoom uit te voeren en als 'voltooid' te markeren, inclusief het resultaat als bijlage.", completed: false },
    { id: 14008, title: "AI Kennismanager", description: "Een AI die de inhoud van alle taken, comments en bijlagen binnen een project indexeert. Gebruikers kunnen dan vragen stellen zoals 'Wat was de laatste beslissing over het login-scherm?' en de AI zoekt het antwoord en geeft de bron.", completed: false },
    { id: 14009, title: "Voorspellende Resource Allocatie", description: "De AI analyseert de aankomende taken en de historische prestaties van teamleden om proactief te waarschuwen voor toekomstige capaciteitsproblemen. Het kan zelfs voorstellen om taken te herverdelen voordat er een knelpunt ontstaat.", completed: false },
    { id: 14010, title: "AI-gestuurde 'Best Next Action'", description: "Een widget op het dashboard die voor elke gebruiker de 'beste volgende taak' suggereert. De AI baseert dit op een combinatie van prioriteit, deadline, afhankelijkheden en de persoonlijke productiviteitspatronen van de gebruiker.", completed: false },
    { id: 14011, title: "Automatische Blocker Detectie", description: "De AI analyseert de tekst van nieuwe taken en comments op zinnen als 'Ik wacht op...' of 'Ik ben geblokkeerd door...'. Indien gedetecteerd, stelt de AI voor om automatisch een afhankelijkheidsrelatie aan te maken met de betreffende taak.", completed: false },
    { id: 14012, title: "AI Coach voor Nieuwe Gebruikers", description: "Een gepersonaliseerde AI-coach die nieuwe gebruikers begeleidt. Het analyseert hun eerste acties en geeft op maat gemaakte tips en suggesties, zoals 'Het lijkt erop dat je veel taken aanmaakt, heb je al overwogen om een template te maken?'.", completed: false },
    { id: 14013, title: "Dynamische Prioriteitsaanpassing", description: "Een optionele AI-agent die de prioriteit van taken dynamisch kan aanpassen op basis van veranderende omstandigheden, zoals een naderende projectdeadline, een toename in commentaar-activiteit, of het toevoegen van het 'Bug'-label.", completed: false },
    { id: 14014, title: "AI-gegenereerde 'Taak Samenvatting van de Dag'", description: "Aan het einde van elke werkdag kan de AI een korte, gepersonaliseerde samenvatting genereren van de voltooide taken, behaalde voortgang en openstaande punten voor elke gebruiker, klaar om te delen in een statusupdate.", completed: false },
    { id: 14015, title: "Cross-project Afhankelijkheidsanalyse", description: "Een AI die de relaties en afhankelijkheden tussen taken in *verschillende* projecten kan analyseren. Het kan waarschuwen als de vertraging van een taak in Project A een directe impact heeft op de deadline van Project B.", completed: false }
  ]
};
