
import type { Phase } from '../types';

export const phase13: Phase = {
  name: "Fase 13: Geavanceerde Enterprise Beveiliging",
  description: "Functies implementeren die voldoen aan de strenge beveiligingseisen van grote organisaties.",
  features: [
    { id: 13001, title: "Single Sign-On (SSO)", description: "Implementeer ondersteuning voor SAML 2.0 en OpenID Connect. Dit stelt grote organisaties in staat om te integreren met hun eigen identity providers zoals Okta, Azure AD, of Auth0 voor naadloze en veilige authenticatie.", completed: false },
    { id: 13002, title: "Geavanceerde Audit Logs", description: "Breid de audit logs uit. Maak het voor beheerders mogelijk om logs te filteren op gebruiker, datum of actie, en deze te exporteren. Implementeer streaming naar externe SIEM-systemen (Security Information and Event Management).", completed: false },
    { id: 13003, title: "Data Loss Prevention (DLP)", description: "Ontwikkel een systeem dat op basis van reguliere expressies kan detecteren wanneer gevoelige informatie (zoals creditcardnummers of burgerservicenummers) in taken of comments wordt geplaatst en dit kan blokkeren of maskeren.", completed: false },
    { id: 13004, title: "E-discovery & Legal Hold", description: "Bied beheerders de mogelijkheid om alle data gerelateerd aan een specifieke gebruiker of project te 'bevriezen' (legal hold). Deze data kan vervolgens worden geëxporteerd in een standaardformaat voor juridische doeleinden.", completed: false },
    { id: 13005, title: "Configureerbaar Sessiebeleid", description: "Geef organisatie-eigenaren de mogelijkheid om een strikter sessiebeleid af te dwingen. Stel een maximale sessieduur (absolute timeout) en een time-out bij inactiviteit (idle timeout) in voor alle leden.", completed: true },
    { id: 13006, title: "SCIM User Provisioning", description: "Ondersteun het SCIM-protocol. Dit maakt het voor grote organisaties mogelijk om het aanmaken, bijwerken en verwijderen van gebruikersaccounts te automatiseren vanuit hun centrale identity provider (zoals Azure AD).", completed: false },
    { id: 13007, title: "Data Residency Opties", description: "Bied klanten de keuze om hun data op te slaan in een specifieke geografische regio (EU of US) om te voldoen aan lokale wet- en regelgeving zoals de GDPR. Dit vereist het opzetten en beheren van meerdere, gescheiden Firebase-projecten.", completed: false },
    { id: 13008, title: "Rolgebaseerde Toegang tot API Sleutels", description: "Sta beheerders toe om te definiëren welke rollen API-sleutels mogen aanmaken en beheren, in plaats van dit te beperken tot een enkele permissie. Dit biedt meer granulaire controle in grote organisaties.", completed: false },
    { id: 13009, title: "Gedetailleerd Wachtwoordbeleid", description: "Geef beheerders de mogelijkheid om een wachtwoordbeleid af te dwingen voor gebruikers die met e-mail/wachtwoord inloggen, inclusief minimale lengte, complexiteitseisen en verloopdatum.", completed: false },
    { id: 13010, title: "Versleuteling-at-Rest Klantsleutels (CMEK)", description: "Voor enterprise-klanten, bied de mogelijkheid om hun eigen encryptiesleutels te gebruiken (via Google Cloud KMS) voor de versleuteling van hun data in Firestore, wat hen volledige controle geeft over de toegang tot hun data.", completed: false },
    { id: 13011, title: "Rapportage van Toegangsrechten", description: "Een dashboard voor beheerders dat een overzicht geeft van 'wie heeft toegang tot wat'. Toon een matrix van gebruikers en projecten/taken om snel te kunnen verifiëren of de toegangsrechten correct zijn geconfigureerd.", completed: false },
    { id: 13012, title: "API Rate Limiting & Throttling", description: "Implementeer een configureerbaar rate limiting-systeem voor de API om misbruik te voorkomen en de stabiliteit van het platform voor alle gebruikers te garanderen. Beheerders kunnen limieten per sleutel of per gebruiker instellen.", completed: false },
    { id: 13013, title: "Domain Claiming & Verificatie", description: "Sta organisaties toe om hun e-maildomein te verifiëren (bv. `acme.com`). Dit zorgt ervoor dat alleen gebruikers met een geverifieerd e-mailadres lid kunnen worden en verhoogt de beveiliging tegen ongeautoriseerde toegang.", completed: false },
    { id: 13014, title: "Gevoelige Actie Notificaties", description: "Stuur automatisch een e-mailnotificatie naar de organisatie-eigenaar wanneer er een hoog-risico actie plaatsvindt, zoals het verwijderen van een project, het aanmaken van een nieuwe API-sleutel met volledige rechten, of het wijzigen van het SSO-beleid.", completed: false },
    { id: 13015, title: "Regelmatige Penetratietesten", description: "Laat de applicatie periodiek testen door een extern, gespecialiseerd beveiligingsbedrijf. Publiceer een samenvatting van de resultaten (na het oplossen van eventuele bevindingen) om het vertrouwen van enterprise-klanten te winnen.", completed: false }
  ]
};
