import { ROLE_ADMIN, ROLE_GUEST, ROLE_MEMBER, ROLE_OWNER } from '@/lib/core/constants';

export const PERMISSIONS = {
  MANAGE_GENERAL_SETTINGS: 'MANAGE_GENERAL_SETTINGS',
  MANAGE_WORKFLOW: 'MANAGE_WORKFLOW',
  MANAGE_ROLES: 'MANAGE_ROLES',
  MANAGE_MEMBERS: 'MANAGE_MEMBERS',
  MANAGE_MEMBER_PERMISSIONS: 'MANAGE_MEMBER_PERMISSIONS',
  MANAGE_PROJECTS: 'MANAGE_PROJECTS',
  MANAGE_PROJECT_ROLES: 'MANAGE_PROJECT_ROLES',
  MANAGE_TEAMS: 'MANAGE_TEAMS',
  CREATE_TASK: 'CREATE_TASK',
  EDIT_TASK: 'EDIT_TASK',
  DELETE_TASK: 'DELETE_TASK',
  ASSIGN_TASK: 'ASSIGN_TASK',
  VIEW_ALL_TASKS: 'VIEW_ALL_TASKS',
  VIEW_AUDIT_LOG: 'VIEW_AUDIT_LOG',
  VIEW_SENSITIVE_DATA: 'VIEW_SENSITIVE_DATA',
  MANAGE_IDEAS: 'MANAGE_IDEAS',
  MANAGE_API_KEYS: 'MANAGE_API_KEYS',
  MANAGE_INTEGRATIONS: 'MANAGE_INTEGRATIONS',
  MANAGE_TEMPLATES: 'MANAGE_TEMPLATES',
  MANAGE_CHECKLISTS: 'MANAGE_CHECKLISTS',
  MANAGE_SECURITY_SETTINGS: 'MANAGE_SECURITY_SETTINGS',
  MANAGE_IP_WHITELIST: 'MANAGE_IP_WHITELIST',
  MANAGE_ANNOUNCEMENTS: 'MANAGE_ANNOUNCEMENTS',
  MANAGE_BRANDING: 'MANAGE_BRANDING',
  MANAGE_SAVED_FILTERS: 'MANAGE_SAVED_FILTERS',
  MANAGE_FEATURE_TOGGLES: 'MANAGE_FEATURE_TOGGLES',
  PIN_ITEMS: 'PIN_ITEMS',
  MANAGE_AUTOMATIONS: 'MANAGE_AUTOMATIONS',
  MANAGE_WEBHOOKS: 'MANAGE_WEBHOOKS',
  MANAGE_GOALS: 'MANAGE_GOALS',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const PERMISSIONS_DESCRIPTIONS: Record<Permission, { name: string, description: string }> = {
  [PERMISSIONS.MANAGE_GENERAL_SETTINGS]: { name: 'Algemene Instellingen Beheren', description: 'Kan de naam van de organisatie aanpassen.' },
  [PERMISSIONS.MANAGE_WORKFLOW]: { name: 'Workflow Beheren', description: 'Kan statussen, labels, prioriteiten en eigen velden aanpassen.' },
  [PERMISSIONS.MANAGE_ROLES]: { name: 'Rollen Beheren', description: 'Kan rollen en hun permissies aanmaken en aanpassen.' },
  [PERMISSIONS.MANAGE_MEMBERS]: { name: 'Leden Beheren', description: 'Kan leden uitnodigen voor en verwijderen uit de organisatie.' },
  [PERMISSIONS.MANAGE_MEMBER_PERMISSIONS]: { name: 'Lid Permissies Beheren', description: 'Kan individuele permissies van leden overschrijven, los van hun rol.' },
  [PERMISSIONS.MANAGE_PROJECTS]: { name: 'Projecten Beheren', description: 'Kan projecten aanmaken, bewerken en verwijderen.' },
  [PERMISSIONS.MANAGE_PROJECT_ROLES]: { name: 'Projectrollen Beheren', description: 'Kan de rol van een gebruiker binnen een specifiek project aanpassen.' },
  [PERMISSIONS.MANAGE_TEAMS]: { name: 'Teams Beheren', description: 'Kan teams aanmaken en de leden van teams beheren.' },
  [PERMISSIONS.CREATE_TASK]: { name: 'Taken Aanmaken', description: 'Kan nieuwe taken aanmaken binnen de organisatie.' },
  [PERMISSIONS.EDIT_TASK]: { name: 'Taken Bewerken', description: 'Kan de details van bestaande taken aanpassen.' },
  [PERMISSIONS.DELETE_TASK]: { name: 'Taken Verwijderen', description: 'Kan taken naar de prullenbak verplaatsen of permanent verwijderen.' },
  [PERMISSIONS.ASSIGN_TASK]: { name: 'Taken Toewijzen', description: 'Kan taken toewijzen aan leden van de organisatie.' },
  [PERMISSIONS.VIEW_ALL_TASKS]: { name: 'Alle Taken Zien', description: 'Kan alle niet-privé taken binnen de organisatie bekijken.' },
  [PERMISSIONS.VIEW_AUDIT_LOG]: { name: 'Audit Log Bekijken', description: 'Heeft toegang tot de audit log met alle acties binnen de organisatie.' },
  [PERMISSIONS.VIEW_SENSITIVE_DATA]: { name: 'Gevoelige Data Zien', description: 'Kan de inhoud van taken zien die als "gevoelig" zijn gemarkeerd.' },
  [PERMISSIONS.MANAGE_IDEAS]: { name: 'Ideeën Beheren', description: 'Kan de status van ideeën in de ideeënbus aanpassen.' },
  [PERMISSIONS.MANAGE_API_KEYS]: { name: 'API Sleutels Beheren', description: 'Kan API-sleutels voor de organisatie aanmaken, inzien en intrekken.' },
  [PERMISSIONS.MANAGE_INTEGRATIONS]: { name: 'Integraties Beheren', description: 'Kan integraties met externe services zoals Slack en GitHub configureren.' },
  [PERMISSIONS.MANAGE_TEMPLATES]: { name: 'Templates Beheren', description: 'Kan taaktemplates voor de organisatie aanmaken, bewerken en verwijderen.' },
  [PERMISSIONS.MANAGE_CHECKLISTS]: { name: 'Checklisten Beheren', description: 'Kan checklist-templates aanmaken, bewerken en verwijderen.' },
  [PERMISSIONS.MANAGE_SECURITY_SETTINGS]: { name: 'Beveiligingsinstellingen Beheren', description: 'Kan sessiebeleid en andere beveiligingsopties beheren.' },
  [PERMISSIONS.MANAGE_IP_WHITELIST]: { name: 'IP Whitelist Beheren', description: 'Kan de lijst met toegestane IP-adressen voor de organisatie beheren.' },
  [PERMISSIONS.MANAGE_ANNOUNCEMENTS]: { name: 'Aankondigingen Beheren', description: 'Kan organisatie-brede aankondigingen plaatsen en verwijderen.' },
  [PERMISSIONS.MANAGE_BRANDING]: { name: 'Branding Beheren', description: 'Kan het uiterlijk, zoals kleuren en logo, van de organisatie aanpassen.' },
  [PERMISSIONS.MANAGE_SAVED_FILTERS]: { name: 'Opgeslagen Filters Beheren', description: 'Kan opgeslagen filters van andere gebruikers verwijderen.' },
  [PERMISSIONS.MANAGE_FEATURE_TOGGLES]: { name: 'Feature Vlaggen Beheren', description: 'Kan kernfunctionaliteiten en integraties voor de organisatie in- of uitschakelen.' },
  [PERMISSIONS.PIN_ITEMS]: { name: 'Items Vastpinnen', description: 'Kan taken en projecten vastpinnen in de zijbalk voor iedereen in de organisatie.' },
  [PERMISSIONS.MANAGE_AUTOMATIONS]: { name: 'Automatiseringen Beheren', description: 'Kan automatiseringen voor de organisatie aanmaken, bewerken en verwijderen.' },
  [PERMISSIONS.MANAGE_WEBHOOKS]: { name: 'Webhooks Beheren', description: 'Kan webhooks voor de organisatie aanmaken, bewerken en verwijderen.' },
  [PERMISSIONS.MANAGE_GOALS]: { name: 'Doelen & Uitdagingen Beheren', description: 'Kan team-brede uitdagingen aanmaken, bewerken en verwijderen.' },
};

export const DEFAULT_ROLES: Record<string, { name: string; permissions: Permission[] }> = {
  [ROLE_OWNER]: {
    name: 'Eigenaar',
    permissions: Object.values(PERMISSIONS),
  },
  [ROLE_ADMIN]: {
    name: 'Beheerder',
    permissions: [
      PERMISSIONS.MANAGE_GENERAL_SETTINGS,
      PERMISSIONS.MANAGE_WORKFLOW,
      PERMISSIONS.MANAGE_ROLES,
      PERMISSIONS.MANAGE_MEMBERS,
      PERMISSIONS.MANAGE_MEMBER_PERMISSIONS,
      PERMISSIONS.MANAGE_PROJECTS,
      PERMISSIONS.MANAGE_PROJECT_ROLES,
      PERMISSIONS.MANAGE_TEAMS,
      PERMISSIONS.CREATE_TASK,
      PERMISSIONS.EDIT_TASK,
      PERMISSIONS.DELETE_TASK,
      PERMISSIONS.ASSIGN_TASK,
      PERMISSIONS.VIEW_ALL_TASKS,
      PERMISSIONS.VIEW_AUDIT_LOG,
      PERMISSIONS.VIEW_SENSITIVE_DATA,
      PERMISSIONS.MANAGE_IDEAS,
      PERMISSIONS.MANAGE_API_KEYS,
      PERMISSIONS.MANAGE_INTEGRATIONS,
      PERMISSIONS.MANAGE_TEMPLATES,
      PERMISSIONS.MANAGE_CHECKLISTS,
      PERMISSIONS.MANAGE_SECURITY_SETTINGS,
      PERMISSIONS.MANAGE_IP_WHITELIST,
      PERMISSIONS.MANAGE_ANNOUNCEMENTS,
      PERMISSIONS.MANAGE_BRANDING,
      PERMISSIONS.MANAGE_SAVED_FILTERS,
      PERMISSIONS.MANAGE_FEATURE_TOGGLES,
      PERMISSIONS.PIN_ITEMS,
      PERMISSIONS.MANAGE_AUTOMATIONS,
      PERMISSIONS.MANAGE_WEBHOOKS,
      PERMISSIONS.MANAGE_GOALS,
    ],
  },
  [ROLE_MEMBER]: {
    name: 'Lid',
    permissions: [
      PERMISSIONS.CREATE_TASK,
      PERMISSIONS.EDIT_TASK,
      PERMISSIONS.VIEW_ALL_TASKS,
      PERMISSIONS.PIN_ITEMS,
    ],
  },
  [ROLE_GUEST]: {
    name: 'Gast',
    permissions: [], // Permissions for guests are handled by data scoping, not a permission flag.
  },
};
export type RoleName = string;
